### ISSUE TITLE
Windows x32 for Electron

### ISSUE THREAD

**Issue by Vj3k0** [DenisCarriere/sqlite3-offline#1]
Hi, great initiative! I see that there is no x32 version for Electron. This is was just missed out, or was there a problem with something?

Thanks. Cheers,
Vjeko

**Comment by DenisCarriere** [comment]
~There is... it's called ia32, does it not work?~ You are correct.
https://github.com/DenisCarriere/sqlite3-offline/tree/master/packages/sqlite3-win32

**Comment by Vj3k0** [comment]
I see:

* electron-v1.5-win32-x64
* electron-v1.6-win32-x64
* electron-v1.7-win32-x64

I see ia32 for node though.

**Comment by DenisCarriere** [comment]
Oh you are correct, I did not publish any x32 for Electron since that process has to be done manually and I've only done it for x64 Electron versions.

**Comment by DenisCarriere** [comment]
Currently [`mapbox/node-sqlite3`](https://github.com/mapbox/node-sqlite3) doesn't publish the Electron binaries, might be worth helping @springmeyer to find an automated approach to build these Electron binaries to their S3 buckets (mentioned here https://github.com/mapbox/node-sqlite3/issues/840)
